### PR TITLE
feat: add support for host - basePath in swagger

### PR DESCRIPTION
**Pull request by alireza-mh**
Just to add basePath and host to the script to make it work with different address endpoints

### CODE REVIEW

**Comment by zoubingwu** [comment]
On what case will you need this? Different backend endpoint but with same api path?

**Comment by marko-hologram** [comment]
> On what case will you need this? Different backend endpoint but with same api path?

I'm not the person implementing this PR, but I can offer a use case I have. For my use case, API is deployed on a different domain compared to frontend, so I don't have a case where I can just call `/api/*` routes from frontend. I need full absolute paths in mock handlers in order for everything to work and would love to get them generated out of the box so that I don't have to manually add them later somehow.

This PR seems to implement just what I need 😄

**Comment by zoubingwu** [comment]
@marko-hologram Are you using any bundlers like webpack/vite? If so have your tried using a proxy? 

Generally I'll start my front-end, for example, on `localhost:3000`, and the backend of course is another origin, there will be cross origin issues if I request to it directly, so I'll set a proxy which is provided out-of-box by the bundlers. I only have to write something like `fetch('/api/user')`, then the request goes to dev server's proxy then pass to the real backend server. 

```js
// for webpack 
module.exports = {
  //...
  devServer: {
    proxy: {
      '/api': 'http://another-domain',
    },
  },
};

// for vite
export default defineConfig({
  server: {
    proxy: {
      '/api/v1': {
        target: 'http://another-domain',
        changeOrigin: true,
      },
    }
  }
})
```

And when you import msw, you have mock definitions like `rest.get('/api/user')`, so the request will be intercepted by the service worker as expected and never reach the dev server.

Add basePath and host to the generated mock definition code is viable but this might need a flag to let users to decide when it should be added otherwise it'll break on some use case.

**Comment by alireza-mh** [comment]
Thanks for the feedback,
I didn't even think about this workaround I could also use a chrome extension to redirect some paths to another address but I thought that maybe configuring the library the way that it would fulfill all the needs would be better and more convenient and maybe more people would try it because this webpack configuration and using the extension is not something that everyone has experience with.
You are also right about the need for the flag. Right now I can't imagine a use case that the swagger host has been set but we would not want to use it. I would be more than happy if you can tell me what are the use cases since I am carious about them.
I can also add flag capability but I think it may not make the library that convenient for newcomers. I think still reading the host from swagger in case there is one that is gonna fulfill most use cases. 
At the end it's your call and I just wanted to help after I configure it for my own need

**Comment by marko-hologram** [comment]
> @marko-hologram Are you using any bundlers like webpack/vite? If so have your tried using a proxy?
> 
> Generally I'll start my front-end, for example, on `localhost:3000`, and the backend of course is another origin, there will be cross origin issues if I request to it directly, so I'll set a proxy which is provided out-of-box by the bundlers. I only have to write something like `fetch('/api/user')`, then the request goes to dev server's proxy then pass to the real backend server.
> 
> ```js
> // for webpack 
> module.exports = {
>   //...
>   devServer: {
>     proxy: {
>       '/api': 'http://another-domain',
>     },
>   },
> };
> 
> // for vite
> export default defineConfig({
>   server: {
>     proxy: {
>       '/api/v1': {
>         target: 'http://another-domain',
>         changeOrigin: true,
>       },
>     }
>   }
> })
> ```
> 
> And when you import msw, you have mock definitions like `rest.get('/api/user')`, so the request will be intercepted by the service worker as expected and never reach the dev server.
> 
> Adding basePath and host to the generated mock definition code is viable but this might need a flag to let users to decide when it should be added otherwise it'll break on some use case.

Hmm yeah I see what you mean, I didn't really think about proxies.

I would love if I could do this ideally and have all paths prefixed with that base url instead of proxying:

```bash
npx msw-auto-mock https://example.com/spec.json --base-url https://somerandomurl.com
```

But proxy might be more flexible in the end.

It's ok if it's out of scope for this library since my case might be uncommon. This generator has already helped me a ton and I cannot expect it to do every little thing I might require 😄

**Comment by zoubingwu** [comment]
> Right now I can't imagine a use case that the swagger host has been set but we would not want to use it.

@alireza-mh Actually I believe that you shouldn't specify the api host in your app code unless you have no choice. The backend may have multiple environment like dev/stage/prod and the host may constantly changing. Set it in you local proxy is much more flexible and maintainable.

**Comment by zoubingwu** [comment]
With a flag like this is absolutely doable and acceptable for me, for example:

```sh
# use somerandomurl as base-url 
npx msw-auto-mock https://example.com/spec.json --base-url https://somerandomurl.com/

# use host in openapi spec as base-url 
npx msw-auto-mock https://example.com/spec.json --base-url 

# no base url will be specified in generated code
npx msw-auto-mock https://example.com/spec.json
```

**Comment by marko-hologram** [comment]
> > Right now I can't imagine a use case that the swagger host has been set but we would not want to use it.
> 
> @alireza-mh Actually I believe that you shouldn't specify the api host in your app code unless you have no choice. The backend may have multiple environment like dev/stage/prod and the host may constantly changing. Set it in you local proxy is a much more flexible and maintainable way to do it.

Yeah totally understand you. Proxy should be more flexible and scalable, but I still might not be able to achieve what I need unfortunately since my routes don't share the same path like `/api` for example. I guess my use case might be a bit uncommon. If you implement this flag that will be awesome and if not I'm still happy with how much this library has helped me 😄

**Comment by zoubingwu** [comment]
> With a flag like this is absolutely doable and acceptable to me, for example:
> 
> ```shell
> # use https://somerandomurl.com/ as base-url 
> npx msw-auto-mock https://example.com/spec.json --base-url https://somerandomurl.com/
> 
> # use host in openapi spec as base-url 
> npx msw-auto-mock https://example.com/spec.json --base-url 
> 
> # no base url will be specified in generated code
> npx msw-auto-mock https://example.com/spec.json
> ```

@alireza-mh @marko-hologram hey I just added this flag and released in v0.6.0, you can upgrade and have a try, any feedbacks are welcome.

**Comment by marko-hologram** [comment]
> > With a flag like this is absolutely doable and acceptable to me, for example:
> > ```shell
> > # use https://somerandomurl.com/ as base-url 
> > npx msw-auto-mock https://example.com/spec.json --base-url https://somerandomurl.com/
> > 
> > # use host in openapi spec as base-url 
> > npx msw-auto-mock https://example.com/spec.json --base-url 
> > 
> > # no base url will be specified in generated code
> > npx msw-auto-mock https://example.com/spec.json
> > ```
> 
> @alireza-mh @marko-hologram hey I just added this flag and released in v0.6.0, you can upgrade and have a try, any feedbacks are welcome.

This works like a charm. Thank you for implementing this! It will make my life way easier now on this particular project 😄

**Pull request closed without merging**
